// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e8637dcc282c405e "DaVinci Watches - Finale", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Laptop' | 'Tablet' | 'Phone' // Variant
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { className, css, fonts } from "./chunks/chunk-QCFKN5BM.js";
import { routes } from "./chunks/chunk-3QCU63GD.js";

// virtual:erreur
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Erreur-aU8Y.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	ResolveLinks,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useRouter,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/kyoEqXCsmNlG3ETAC1af/EpwcWj3T2RTmMuVUkscf/iqKpwvLsS.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	BGcPS_lXp: {
		hover: true,
	},
	STDSJsal7: {
		hover: true,
	},
	UEo7B2o26: {
		hover: true,
	},
};
var cycleOrder = ["UEo7B2o26", "BGcPS_lXp", "STDSJsal7"];
var serializationHash = "framer-XckQX";
var variantClassNames = {
	BGcPS_lXp: "framer-v-gco7i3",
	STDSJsal7: "framer-v-1ewy0at",
	UEo7B2o26: "framer-v-12rlmgh",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Button Mini": "STDSJsal7",
	Fill: "BGcPS_lXp",
	Outline: "UEo7B2o26",
};
var getProps = ({ height, id, link, newTab, text, width, ...props }) => {
	return {
		...props,
		MQz7F6Pb7: text ?? props.MQz7F6Pb7 ?? "Button",
		PhjHhuR66: link ?? props.PhjHhuR66,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "UEo7B2o26",
		Xplrk679X: newTab ?? props.Xplrk679X,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		MQz7F6Pb7,
		PhjHhuR66,
		Xplrk679X,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "UEo7B2o26",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={PhjHhuR66}
						motionChild={true}
						nodeId={"UEo7B2o26"}
						openInNewTab={Xplrk679X}
						scopeId={"iqKpwvLsS"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-12rlmgh", className2, classNames)} framer-159cflk`}
							data-border={true}
							data-framer-name={"Outline"}
							layoutDependency={layoutDependency}
							layoutId={"UEo7B2o26"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-f2281524-6303-4e84-a900-a9a142ab836c, rgb(177, 181, 143))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor: "rgba(0, 0, 0, 0)",
								borderBottomLeftRadius: 50,
								borderBottomRightRadius: 50,
								borderTopLeftRadius: 50,
								borderTopRightRadius: 50,
								...style,
							}}
							variants={{
								"BGcPS_lXp-hover": {
									backgroundColor:
										"var(--token-e6782f6a-b44b-4738-a3a9-849005d3c0f5, rgb(139, 107, 48))",
								},
								"STDSJsal7-hover": {
									backgroundColor:
										"var(--token-e6782f6a-b44b-4738-a3a9-849005d3c0f5, rgb(139, 107, 48))",
								},
								"UEo7B2o26-hover": {
									"--border-color": "rgb(171, 146, 106)",
									backgroundColor:
										"var(--token-e6782f6a-b44b-4738-a3a9-849005d3c0f5, rgb(171, 146, 106))",
								},
								BGcPS_lXp: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor:
										"var(--token-f2281524-6303-4e84-a900-a9a142ab836c, rgb(215, 190, 142))",
								},
								STDSJsal7: {
									backgroundColor: "rgba(0, 0, 0, 0)",
								},
							}}
							{...addPropertyOverrides(
								{
									"BGcPS_lXp-hover": {
										"data-framer-name": void 0,
									},
									"STDSJsal7-hover": {
										"data-framer-name": void 0,
									},
									"UEo7B2o26-hover": {
										"data-framer-name": void 0,
									},
									BGcPS_lXp: {
										"data-framer-name": "Fill",
									},
									STDSJsal7: {
										"data-framer-name": "Button Mini",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1x14ia4"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"YVoEy3ySy"}
								style={{
									"--extracted-r6o4lv": "rgb(61, 61, 61)",
									"--framer-paragraph-spacing": "0px",
								}}
								text={MQz7F6Pb7}
								variants={{
									"BGcPS_lXp-hover": {
										"--extracted-r6o4lv":
											"var(--token-ce16a6ab-b965-4173-bcd7-639c448a6533, rgb(255, 255, 255))",
									},
									"STDSJsal7-hover": {
										"--extracted-r6o4lv":
											"var(--token-ce16a6ab-b965-4173-bcd7-639c448a6533, rgb(255, 255, 255))",
									},
									"UEo7B2o26-hover": {
										"--extracted-r6o4lv":
											"var(--token-ce16a6ab-b965-4173-bcd7-639c448a6533, rgb(255, 255, 255))",
									},
									BGcPS_lXp: {
										"--extracted-r6o4lv":
											"var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, rgb(30, 30, 30))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"BGcPS_lXp-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1er78qb"}
														data-styles-preset={"d0WA5d5b_"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-ce16a6ab-b965-4173-bcd7-639c448a6533, rgb(255, 255, 255)))",
														}}
													>
														{"Button"}
													</motion.p>
												</React.Fragment>
											),
										},
										"STDSJsal7-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1er78qb"}
														data-styles-preset={"d0WA5d5b_"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-ce16a6ab-b965-4173-bcd7-639c448a6533, rgb(255, 255, 255)))",
														}}
													>
														{"Button"}
													</motion.p>
												</React.Fragment>
											),
										},
										"UEo7B2o26-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1er78qb"}
														data-styles-preset={"d0WA5d5b_"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-ce16a6ab-b965-4173-bcd7-639c448a6533, rgb(255, 255, 255)))",
														}}
													>
														{"Button"}
													</motion.p>
												</React.Fragment>
											),
										},
										BGcPS_lXp: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1er78qb"}
														data-styles-preset={"d0WA5d5b_"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, rgb(30, 30, 30)))",
														}}
													>
														{"Button"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1er78qb"}
										data-styles-preset={"d0WA5d5b_"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(61, 61, 61))",
										}}
									>
										{"Button"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-XckQX.framer-159cflk, .framer-XckQX .framer-159cflk { display: block; }",
	".framer-XckQX.framer-12rlmgh { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 16px 32px 16px 32px; position: relative; text-decoration: none; width: min-content; }",
	".framer-XckQX .framer-1x14ia4 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-XckQX.framer-v-1ewy0at.framer-12rlmgh { padding: 8px 16px 8px 16px; }",
	...css,
	'.framer-XckQX[data-border="true"]::after, .framer-XckQX [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FrameriqKpwvLsS = withCSS(Component, css2, "framer-XckQX");
var stdin_default = FrameriqKpwvLsS;
FrameriqKpwvLsS.displayName = "BoutonVD";
FrameriqKpwvLsS.defaultProps = {
	height: 57.5,
	width: 113,
};
addPropertyControls(FrameriqKpwvLsS, {
	variant: {
		options: ["UEo7B2o26", "BGcPS_lXp", "STDSJsal7"],
		optionTitles: ["Outline", "Fill", "Button Mini"],
		title: "Variant",
		type: ControlType.Enum,
	},
	MQz7F6Pb7: {
		defaultValue: "Button",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	PhjHhuR66: {
		title: "Link",
		type: ControlType.Link,
	},
	Xplrk679X: {
		defaultValue: false,
		title: "New Tab",
		type: ControlType.Boolean,
	},
});
addFonts(
	FrameriqKpwvLsS,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framer.com/m/Erreur-aU8Y.js
var BoutonVDFonts = getFonts(stdin_default);
var cycleOrder2 = ["fFDbgl8Nn", "KGuF0tcrA", "DK0VzkL32", "M8XFcVgvD"];
var serializationHash2 = "framer-PBS5W";
var variantClassNames2 = {
	DK0VzkL32: "framer-v-1kue393",
	fFDbgl8Nn: "framer-v-qxgqi0",
	KGuF0tcrA: "framer-v-284t1z",
	M8XFcVgvD: "framer-v-1vh1ks",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	Desktop: "fFDbgl8Nn",
	Laptop: "KGuF0tcrA",
	Phone: "M8XFcVgvD",
	Tablet: "DK0VzkL32",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "fFDbgl8Nn",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "fFDbgl8Nn",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "KGuF0tcrA") return false;
		return true;
	};
	const router = useRouter();
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.section
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-qxgqi0",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"fFDbgl8Nn"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-3399e391-f9d3-4781-bcc9-e38e7cf0c7f5, rgb(249, 253, 254))",
							...style,
						}}
						{...addPropertyOverrides2(
							{
								DK0VzkL32: {
									"data-framer-name": "Tablet",
								},
								KGuF0tcrA: {
									"data-framer-name": "Laptop",
								},
								M8XFcVgvD: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<RichText2
								__fromCanvasComponent={true}
								className={"framer-13ka4no"}
								fonts={["CUSTOM;Adam Bold Bold"]}
								layoutDependency={layoutDependency}
								layoutId={"QukVegozh"}
								style={{
									"--extracted-gdpscs":
										"var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, rgb(30, 30, 30))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.h1
										style={{
											"--font-selector": "Q1VTVE9NO0FkYW0gQm9sZCBCb2xk",
											"--framer-font-family":
												'"Adam Bold Bold", "Adam Bold Bold Placeholder", sans-serif',
											"--framer-font-size": "61px",
											"--framer-letter-spacing": "-0.04em",
											"--framer-line-height": "1.33em",
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-gdpscs, var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, rgb(30, 30, 30)))",
										}}
									>
										{"Cette page n'existe pas"}
									</motion2.h1>
								</React2.Fragment>
							</RichText2>
						)}
						{isDisplayed() && (
							<ResolveLinks
								links={[
									{
										href: {
											webPageId: "HqqUpNGKj",
										},
										implicitPathVariables: void 0,
									},
									{
										href: {
											webPageId: "HqqUpNGKj",
										},
										implicitPathVariables: void 0,
									},
									{
										href: {
											webPageId: "HqqUpNGKj",
										},
										implicitPathVariables: void 0,
									},
								]}
							>
								{(resolvedLinks) => (
									<ComponentViewportProvider
										height={57}
										y={
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 528) - 0 - 197.13) / 2 +
												81.13 +
												59)
										}
										{...addPropertyOverrides2(
											{
												DK0VzkL32: {
													y:
														(componentViewport?.y || 0) +
														160 +
														(((componentViewport?.height || 528) -
															160 -
															197.13) /
															2 +
															81.13 +
															59),
												},
												M8XFcVgvD: {
													y:
														(componentViewport?.y || 0) +
														160 +
														(((componentViewport?.height || 528) -
															160 -
															197.13) /
															2 +
															81.13 +
															59),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1na1y2h-container"}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"uowT49uzZ-container"}
											nodeId={"uowT49uzZ"}
											rendersWithMotion={true}
											scopeId={"eU8YsCycq"}
										>
											{_jsx2(stdin_default, {
												height: "100%",
												id: "uowT49uzZ",
												layoutId: "uowT49uzZ",
												MQz7F6Pb7: "Emmenez-moi \xE0 l'accueil",
												PhjHhuR66: resolvedLinks[0],
												variant: "UEo7B2o26",
												width: "100%",
												Xplrk679X: false,
												...addPropertyOverrides2(
													{
														DK0VzkL32: {
															PhjHhuR66: resolvedLinks[1],
														},
														M8XFcVgvD: {
															PhjHhuR66: resolvedLinks[2],
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</ResolveLinks>
						)}
					</motion2.section>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-PBS5W.framer-1upwfr2, .framer-PBS5W .framer-1upwfr2 { display: block; }",
	".framer-PBS5W.framer-qxgqi0 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 59px; height: min-content; justify-content: center; min-height: calc(var(--framer-viewport-height, 100vh) * 0.66); overflow: visible; padding: 0px 64px 0px 64px; position: relative; width: 1560px; }",
	".framer-PBS5W .framer-13ka4no { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-PBS5W .framer-1na1y2h-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-PBS5W.framer-v-284t1z.framer-qxgqi0 { padding: 160px 64px 0px 64px; width: 1200px; }",
	".framer-PBS5W.framer-v-1kue393.framer-qxgqi0 { padding: 160px 64px 0px 64px; width: 810px; }",
	".framer-PBS5W.framer-v-1vh1ks.framer-qxgqi0 { padding: 160px 64px 0px 64px; width: 390px; }",
];
var FramereU8YsCycq = withCSS2(Component2, css3, "framer-PBS5W");
var stdin_default2 = FramereU8YsCycq;
FramereU8YsCycq.displayName = "Erreur";
FramereU8YsCycq.defaultProps = {
	height: 528,
	width: 1560,
};
addPropertyControls2(FramereU8YsCycq, {
	variant: {
		options: ["fFDbgl8Nn", "KGuF0tcrA", "DK0VzkL32", "M8XFcVgvD"],
		optionTitles: ["Desktop", "Laptop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramereU8YsCycq,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Adam Bold Bold",
					source: "custom",
					url: "https://framerusercontent.com/assets/asCTCF4ToTxAfbTwnPHZUy0.woff2",
				},
			],
		},
		...BoutonVDFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:erreur
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "M8XFcVgvD",
	md: "DK0VzkL32",
	xl: "KGuF0tcrA",
	"2xl": "fFDbgl8Nn",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e8637dcc282c405e8332e4eab2cb458a196f99fcac27567df85b0de9996f5033"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders ErreurFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e8637dcc282c405e8332e4eab2cb458a196f99fcac27567df85b0de9996f5033"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var erreur_default = ComponentWithRoot;
export { erreur_default as default };
