// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e8637dcc282c405e "DaVinci Watches - Finale", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Laptop' | 'Tablet' | 'Phone' // Variant
 * questionUn?: string // QuestionUn
 * reponseUn?: string // ReponseUn
 * questionDeux?: string // QuestionDeux
 * reponseDeux?: string // ReponseDeux
 * questionTrois?: string // QuestionTrois
 * reponseTrois?: string // ReponseTrois
 * questionQuatre?: string // QuestionQuatre
 * reponseQuatre?: string // ReponseQuatre
 * questionCinq?: string // QuestionCinq
 * reponseCinq?: string // ReponseCinq
 * questionSix?: string // QuestionSix
 * reponseSix?: string // ReponseSix
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { className, css, fonts } from "./chunks/chunk-6EOOJZE3.js";
import { Icon } from "./chunks/chunk-NLM6TSV4.js";
import "./chunks/chunk-BVM6H744.js";
import { routes } from "./chunks/chunk-3QCU63GD.js";

// virtual:faq
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/FAQ-fcbv.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	RichText as RichText2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/jp3fKgdUYpqUFmi78jUT/Pj1uyOwQuVD5yCr7gAhE/xkgf3NWgk.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/d0VPT038NdSvJ1HoOfNQ/mOAnGBQquRvRF9PaBDn1/FfbbwYOZg.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;Hedvig Letters Sans-regular",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Hedvig Letters Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/hedvigletterssans/v2/CHy_V_PfGVjobSBkihHWDT98RVp37w8jQJhN3Twgi1w.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://app.framerstatic.com/Inter-Bold.cyrillic-ext-XOTVL7ZR.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://app.framerstatic.com/Inter-Bold.cyrillic-6LOMBC2V.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://app.framerstatic.com/Inter-Bold.greek-ext-WXWSJXLB.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://app.framerstatic.com/Inter-Bold.greek-YRST7ODZ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://app.framerstatic.com/Inter-Bold.latin-ext-BASA5UL3.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://app.framerstatic.com/Inter-Bold.latin-UCM45LQF.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://app.framerstatic.com/Inter-Bold.vietnamese-OEVJMXEP.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://app.framerstatic.com/Inter-BoldItalic.cyrillic-ext-PEYDHC3S.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://app.framerstatic.com/Inter-BoldItalic.cyrillic-7EIL6JWG.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://app.framerstatic.com/Inter-BoldItalic.greek-ext-3DJOYQMH.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://app.framerstatic.com/Inter-BoldItalic.greek-TJBTLTT7.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://app.framerstatic.com/Inter-BoldItalic.latin-ext-FVPCPRBJ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://app.framerstatic.com/Inter-BoldItalic.latin-5ZFQS4XK.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://app.framerstatic.com/Inter-BoldItalic.vietnamese-W2625PGF.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://app.framerstatic.com/Inter-Italic.cyrillic-ext-YDGMJOJO.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://app.framerstatic.com/Inter-Italic.cyrillic-BFOVMAQB.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://app.framerstatic.com/Inter-Italic.greek-ext-4KOU3AHC.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://app.framerstatic.com/Inter-Italic.greek-OJTBJNE6.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://app.framerstatic.com/Inter-Italic.latin-ext-H4B22QN6.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://app.framerstatic.com/Inter-Italic.latin-2DWX32EN.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://app.framerstatic.com/Inter-Italic.vietnamese-TYMT6CKW.woff2",
				weight: "400",
			},
		],
	},
];
var css2 = [
	'.framer-ZByps .framer-styles-preset-17bssob:not(.rich-text-wrapper), .framer-ZByps .framer-styles-preset-17bssob.rich-text-wrapper p { --framer-font-family: "Hedvig Letters Sans", "Hedvig Letters Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-size: 25px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, #1e1e1e); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1559px) and (min-width: 1200px) { .framer-ZByps .framer-styles-preset-17bssob:not(.rich-text-wrapper), .framer-ZByps .framer-styles-preset-17bssob.rich-text-wrapper p { --framer-font-family: "Hedvig Letters Sans", "Hedvig Letters Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-size: 23px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, #1e1e1e); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-ZByps .framer-styles-preset-17bssob:not(.rich-text-wrapper), .framer-ZByps .framer-styles-preset-17bssob.rich-text-wrapper p { --framer-font-family: "Hedvig Letters Sans", "Hedvig Letters Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-size: 22px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, #1e1e1e); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-ZByps .framer-styles-preset-17bssob:not(.rich-text-wrapper), .framer-ZByps .framer-styles-preset-17bssob.rich-text-wrapper p { --framer-font-family: "Hedvig Letters Sans", "Hedvig Letters Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, #1e1e1e); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className2 = "framer-ZByps";

// /:https://framerusercontent.com/modules/jp3fKgdUYpqUFmi78jUT/Pj1uyOwQuVD5yCr7gAhE/xkgf3NWgk.js
var PhosphorFonts = getFonts(Icon);
var cycleOrder = ["E2PKHp_2l", "GNe6SLWcd"];
var serializationHash = "framer-Oeocm";
var variantClassNames = {
	E2PKHp_2l: "framer-v-3u9mxg",
	GNe6SLWcd: "framer-v-98mqm2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Closed: "GNe6SLWcd",
	Open: "E2PKHp_2l",
};
var getProps = ({ answer, height, id, question, width, ...props }) => {
	return {
		...props,
		gweFQuELC:
			answer ??
			props.gweFQuELC ??
			"You can make a reservation directly through our website or by contacting our reservations team via phone or email. We also accept bookings through third-party booking platforms.",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "E2PKHp_2l",
		x2_Q5XkAe:
			question ??
			props.x2_Q5XkAe ??
			"How can I make a reservation at your hotel?",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		x2_Q5XkAe,
		gweFQuELC,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "E2PKHp_2l",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap14n34mm = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("GNe6SLWcd");
	});
	const onTap6xhasi = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("E2PKHp_2l");
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "GNe6SLWcd") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-3u9mxg",
							className3,
							classNames,
						)}
						data-framer-name={"Open"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"E2PKHp_2l"}
						onTap={onTap14n34mm}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								GNe6SLWcd: {
									"data-framer-name": "Closed",
									onTap: onTap6xhasi,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1gyv0p8"}
							layoutDependency={layoutDependency}
							layoutId={"MhgSzHLNc"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1g0tpiu"}
								data-framer-name={"Question"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"SDx8Yi6J8"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={x2_Q5XkAe}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-17bssob"}
										data-styles-preset={"FfbbwYOZg"}
									>
										{"How can I make a reservation at your hotel?"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-8dasqg-container"}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"xILkkQKTi-container"}
									nodeId={"xILkkQKTi"}
									rendersWithMotion={true}
									scopeId={"xkgf3NWgk"}
									style={{
										rotate: 0,
									}}
									variants={{
										GNe6SLWcd: {
											rotate: 180,
										},
									}}
								>
									<Icon
										color={"rgb(46, 46, 46)"}
										height={"100%"}
										iconSearch={"House"}
										iconSelection={"CaretUp"}
										id={"xILkkQKTi"}
										layoutId={"xILkkQKTi"}
										mirrored={false}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										weight={"regular"}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
						{isDisplayed() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1xmqsg"}
								data-framer-name={"Answer"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"GbE7x7Kn9"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={gweFQuELC}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1er78qb"}
										data-styles-preset={"d0WA5d5b_"}
									>
										{
											"You can make a reservation directly through our website or by contacting our reservations team via phone or email. We also accept bookings through third-party booking platforms."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						)}
						<motion.div
							className={"framer-xq0wmn"}
							data-framer-name={"Line"}
							layoutDependency={layoutDependency}
							layoutId={"VrbCsZUME"}
							style={{
								backgroundColor: "rgb(46, 46, 46)",
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Oeocm.framer-16u33ji, .framer-Oeocm .framer-16u33ji { display: block; }",
	".framer-Oeocm.framer-3u9mxg { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 700px; }",
	".framer-Oeocm .framer-1gyv0p8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-Oeocm .framer-1g0tpiu { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-Oeocm .framer-8dasqg-container { flex: none; height: 32px; position: relative; width: 32px; }",
	".framer-Oeocm .framer-1xmqsg { flex: none; height: auto; max-width: 600px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-Oeocm .framer-xq0wmn { flex: none; height: 1px; overflow: hidden; position: relative; width: 100%; }",
	...css2,
	...css,
];
var Framerxkgf3NWgk = withCSS(Component, css3, "framer-Oeocm");
var stdin_default = Framerxkgf3NWgk;
Framerxkgf3NWgk.displayName = "Accordion";
Framerxkgf3NWgk.defaultProps = {
	height: 172,
	width: 700,
};
addPropertyControls(Framerxkgf3NWgk, {
	variant: {
		options: ["E2PKHp_2l", "GNe6SLWcd"],
		optionTitles: ["Open", "Closed"],
		title: "Variant",
		type: ControlType.Enum,
	},
	x2_Q5XkAe: {
		defaultValue: "How can I make a reservation at your hotel?",
		displayTextArea: true,
		placeholder: "",
		title: "Question",
		type: ControlType.String,
	},
	gweFQuELC: {
		defaultValue:
			"You can make a reservation directly through our website or by contacting our reservations team via phone or email. We also accept bookings through third-party booking platforms.",
		displayTextArea: true,
		title: "Answer",
		type: ControlType.String,
	},
});
addFonts(
	Framerxkgf3NWgk,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framer.com/m/FAQ-fcbv.js
var AccordionFonts = getFonts2(stdin_default);
var MotionDivWithFX = withFX(motion2.div);
var cycleOrder2 = ["fdMpW_bv9", "Q8gO0cTJA", "vfHOM_tY3", "XiJfXJHW0"];
var serializationHash2 = "framer-o6Mjh";
var variantClassNames2 = {
	fdMpW_bv9: "framer-v-1jnb3f6",
	Q8gO0cTJA: "framer-v-og98it",
	vfHOM_tY3: "framer-v-1yx5yko",
	XiJfXJHW0: "framer-v-l4i17p",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 150,
};
var transition2 = {
	damping: 50,
	delay: 0,
	mass: 1,
	stiffness: 100,
	type: "spring",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 150,
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	Desktop: "fdMpW_bv9",
	Laptop: "Q8gO0cTJA",
	Phone: "XiJfXJHW0",
	Tablet: "vfHOM_tY3",
};
var getProps2 = ({
	height,
	id,
	questionCinq,
	questionDeux,
	questionQuatre,
	questionSix,
	questionTrois,
	questionUn,
	reponseCinq,
	reponseDeux,
	reponseQuatre,
	reponseSix,
	reponseTrois,
	reponseUn,
	width,
	...props
}) => {
	return {
		...props,
		AgVIZixiY:
			reponseDeux ??
			props.AgVIZixiY ??
			"Absolument. Nos montres b\xE9n\xE9ficient d\u2019une garantie commerciale allant de 12 \xE0 24 mois, selon le mod\xE8le et son \xE9tat. Les d\xE9tails sont pr\xE9cis\xE9s lors de l\u2019achat.",
		bgkvim21n:
			reponseSix ??
			props.bgkvim21n ??
			"Oui, sous conditions. Nos experts \xE9valueront l\u2019authenticit\xE9 et l\u2019\xE9tat de la montre. La pr\xE9sence des papiers et de la bo\xEEte reste un atout pour maximiser la valeur.",
		cOY7DLCd7:
			reponseCinq ??
			props.cOY7DLCd7 ??
			"Oui. Nous assurons des livraisons s\xE9curis\xE9es en France et en Europe sous 24h \xE0 48h, via des transporteurs sp\xE9cialis\xE9s et assur\xE9s, avec suivi complet.",
		dGtOSqQm4:
			questionDeux ??
			props.dGtOSqQm4 ??
			"Proposez-vous une garantie sur les montres vendues ?",
		IdvJ8eZXu:
			questionCinq ??
			props.IdvJ8eZXu ??
			"Exp\xE9diez-vous \xE0 l\u2019international ?",
		JXlflnerm:
			reponseUn ??
			props.JXlflnerm ??
			"Oui. Chaque montre est rigoureusement authentifi\xE9e par nos horlogers experts avant d\u2019\xEAtre mise en vente. Un certificat d\u2019authenticit\xE9 est d\xE9livr\xE9 pour chaque pi\xE8ce.",
		KEz9G5LNo:
			reponseQuatre ??
			props.KEz9G5LNo ??
			"Oui. Si un mod\xE8le n\u2019est pas disponible en stock, nous proposons un service de sourcing personnalis\xE9 pour trouver la pi\xE8ce exacte que vous recherchez.",
		mfph44fFR:
			questionTrois ??
			props.mfph44fFR ??
			"Puis-je faire estimer ma montre gratuitement ?",
		qGQchHvpF:
			questionQuatre ??
			props.qGQchHvpF ??
			"Est-il possible de rechercher un mod\xE8le sp\xE9cifique ?",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "fdMpW_bv9",
		WAQHLu5Ew:
			questionUn ??
			props.WAQHLu5Ew ??
			"Toutes les montres sont-elles authentifi\xE9es ?",
		Wmsh2RifY:
			questionSix ??
			props.Wmsh2RifY ??
			"Rachetez-vous les montres sans bo\xEEte ni papiers ?",
		zHKv5VQZb:
			reponseTrois ??
			props.zHKv5VQZb ??
			"Oui. Nous proposons un service d\u2019estimation gratuit, en boutique ou \xE0 distance via photos et r\xE9f\xE9rences. Un rendez-vous peut \xEAtre n\xE9cessaire pour une \xE9valuation pr\xE9cise.",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		WAQHLu5Ew,
		JXlflnerm,
		dGtOSqQm4,
		AgVIZixiY,
		mfph44fFR,
		zHKv5VQZb,
		qGQchHvpF,
		KEz9G5LNo,
		IdvJ8eZXu,
		cOY7DLCd7,
		Wmsh2RifY,
		bgkvim21n,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "fdMpW_bv9",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.section
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1jnb3f6",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"fdMpW_bv9"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-3399e391-f9d3-4781-bcc9-e38e7cf0c7f5, rgb(249, 253, 254))",
							...style,
						}}
						{...addPropertyOverrides2(
							{
								Q8gO0cTJA: {
									"data-framer-name": "Laptop",
								},
								vfHOM_tY3: {
									"data-framer-name": "Tablet",
								},
								XiJfXJHW0: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-fdmkpz"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"pqvPZbnfZ"}
						>
							<motion2.div
								className={"framer-1ha7crw"}
								layoutDependency={layoutDependency}
								layoutId={"z2G6eOwLE"}
							>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-1hylm0d"}
									data-framer-name={"Heading"}
									fonts={["CUSTOM;Adam Medium Medium"]}
									layoutDependency={layoutDependency}
									layoutId={"BQmEjCDCT"}
									style={{
										"--extracted-1of0zx5":
											"var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, rgb(30, 30, 30))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.h2
											style={{
												"--font-selector":
													"Q1VTVE9NO0FkYW0gTWVkaXVtIE1lZGl1bQ==",
												"--framer-font-family":
													'"Adam Medium Medium", "Adam Medium Medium Placeholder", sans-serif',
												"--framer-font-size": "49px",
												"--framer-letter-spacing": "-0.02em",
												"--framer-line-height": "1.33em",
												"--framer-text-color":
													"var(--extracted-1of0zx5, var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, rgb(30, 30, 30)))",
											}}
										>
											{"FAQ"}
										</motion2.h2>
									</React2.Fragment>
								</RichText2>
								<MotionDivWithFX
									__framer__animate={{
										transition: transition2,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__exit={animation1}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-19w8ofe"}
									data-framer-name={"Questions"}
									layoutDependency={layoutDependency}
									layoutId={"DUq88iikO"}
								>
									<motion2.div
										className={"framer-vo31t8"}
										data-framer-name={"Left"}
										layoutDependency={layoutDependency}
										layoutId={"xWojRLX8E"}
									>
										<ComponentViewportProvider2
											height={172}
											width={`max((max(min(max(${componentViewport?.width || "100vw"} - 128px, 1px), 1640px), 1px) - 32px) / 2, 1px)`}
											y={
												(componentViewport?.y || 0) +
												52 +
												0 +
												0 +
												145.17 +
												0 +
												0 +
												0
											}
											{...addPropertyOverrides2(
												{
													vfHOM_tY3: {
														width: `max(min(max(${componentViewport?.width || "100vw"} - 80px, 1px), 1640px), 1px)`,
														y:
															(componentViewport?.y || 0) +
															52 +
															0 +
															0 +
															145.17 +
															0 +
															0 +
															0 +
															0,
													},
													XiJfXJHW0: {
														width: `max(min(max(${componentViewport?.width || "100vw"} - 48px, 1px), 1640px), 1px)`,
														y:
															(componentViewport?.y || 0) +
															96 +
															0 +
															0 +
															129.17 +
															0 +
															0 +
															0 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer2
												className={"framer-1hou1w6-container"}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"Qt5Ew7fpF-container"}
												nodeId={"Qt5Ew7fpF"}
												rendersWithMotion={true}
												scopeId={"DRR7m6of2"}
											>
												{_jsx2(stdin_default, {
													gweFQuELC: JXlflnerm,
													height: "100%",
													id: "Qt5Ew7fpF",
													layoutId: "Qt5Ew7fpF",
													style: {
														width: "100%",
													},
													variant: "E2PKHp_2l",
													width: "100%",
													x2_Q5XkAe: WAQHLu5Ew,
												})}
											</SmartComponentScopedContainer2>
										</ComponentViewportProvider2>
										<ComponentViewportProvider2
											height={172}
											width={`max((max(min(max(${componentViewport?.width || "100vw"} - 128px, 1px), 1640px), 1px) - 32px) / 2, 1px)`}
											y={
												(componentViewport?.y || 0) +
												52 +
												0 +
												0 +
												145.17 +
												0 +
												0 +
												204
											}
											{...addPropertyOverrides2(
												{
													vfHOM_tY3: {
														width: `max(min(max(${componentViewport?.width || "100vw"} - 80px, 1px), 1640px), 1px)`,
														y:
															(componentViewport?.y || 0) +
															52 +
															0 +
															0 +
															145.17 +
															0 +
															0 +
															0 +
															204,
													},
													XiJfXJHW0: {
														width: `max(min(max(${componentViewport?.width || "100vw"} - 48px, 1px), 1640px), 1px)`,
														y:
															(componentViewport?.y || 0) +
															96 +
															0 +
															0 +
															129.17 +
															0 +
															0 +
															0 +
															204,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer2
												className={"framer-o5k493-container"}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"JhJa3tdIj-container"}
												nodeId={"JhJa3tdIj"}
												rendersWithMotion={true}
												scopeId={"DRR7m6of2"}
											>
												{_jsx2(stdin_default, {
													gweFQuELC: AgVIZixiY,
													height: "100%",
													id: "JhJa3tdIj",
													layoutId: "JhJa3tdIj",
													style: {
														width: "100%",
													},
													variant: "GNe6SLWcd",
													width: "100%",
													x2_Q5XkAe: dGtOSqQm4,
												})}
											</SmartComponentScopedContainer2>
										</ComponentViewportProvider2>
										<ComponentViewportProvider2
											height={172}
											width={`max((max(min(max(${componentViewport?.width || "100vw"} - 128px, 1px), 1640px), 1px) - 32px) / 2, 1px)`}
											y={
												(componentViewport?.y || 0) +
												52 +
												0 +
												0 +
												145.17 +
												0 +
												0 +
												408
											}
											{...addPropertyOverrides2(
												{
													vfHOM_tY3: {
														width: `max(min(max(${componentViewport?.width || "100vw"} - 80px, 1px), 1640px), 1px)`,
														y:
															(componentViewport?.y || 0) +
															52 +
															0 +
															0 +
															145.17 +
															0 +
															0 +
															0 +
															408,
													},
													XiJfXJHW0: {
														width: `max(min(max(${componentViewport?.width || "100vw"} - 48px, 1px), 1640px), 1px)`,
														y:
															(componentViewport?.y || 0) +
															96 +
															0 +
															0 +
															129.17 +
															0 +
															0 +
															0 +
															408,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer2
												className={"framer-mb5kce-container"}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"tKyLBjKF4-container"}
												nodeId={"tKyLBjKF4"}
												rendersWithMotion={true}
												scopeId={"DRR7m6of2"}
											>
												{_jsx2(stdin_default, {
													gweFQuELC: zHKv5VQZb,
													height: "100%",
													id: "tKyLBjKF4",
													layoutId: "tKyLBjKF4",
													style: {
														width: "100%",
													},
													variant: "GNe6SLWcd",
													width: "100%",
													x2_Q5XkAe: mfph44fFR,
												})}
											</SmartComponentScopedContainer2>
										</ComponentViewportProvider2>
									</motion2.div>
									<motion2.div
										className={"framer-mihys"}
										data-framer-name={"Right"}
										layoutDependency={layoutDependency}
										layoutId={"weGl98AZQ"}
									>
										<ComponentViewportProvider2
											height={172}
											width={`max((max(min(max(${componentViewport?.width || "100vw"} - 128px, 1px), 1640px), 1px) - 32px) / 2, 1px)`}
											y={
												(componentViewport?.y || 0) +
												52 +
												0 +
												0 +
												145.17 +
												0 +
												0 +
												0
											}
											{...addPropertyOverrides2(
												{
													vfHOM_tY3: {
														width: `max(min(max(${componentViewport?.width || "100vw"} - 80px, 1px), 1640px), 1px)`,
														y:
															(componentViewport?.y || 0) +
															52 +
															0 +
															0 +
															145.17 +
															0 +
															612 +
															0 +
															0,
													},
													XiJfXJHW0: {
														width: `max(min(max(${componentViewport?.width || "100vw"} - 48px, 1px), 1640px), 1px)`,
														y:
															(componentViewport?.y || 0) +
															96 +
															0 +
															0 +
															129.17 +
															0 +
															612 +
															0 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer2
												className={"framer-1bpl0ko-container"}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"R_KE0bHeG-container"}
												nodeId={"R_KE0bHeG"}
												rendersWithMotion={true}
												scopeId={"DRR7m6of2"}
											>
												{_jsx2(stdin_default, {
													gweFQuELC: KEz9G5LNo,
													height: "100%",
													id: "R_KE0bHeG",
													layoutId: "R_KE0bHeG",
													style: {
														width: "100%",
													},
													variant: "GNe6SLWcd",
													width: "100%",
													x2_Q5XkAe: qGQchHvpF,
												})}
											</SmartComponentScopedContainer2>
										</ComponentViewportProvider2>
										<ComponentViewportProvider2
											height={172}
											width={`max((max(min(max(${componentViewport?.width || "100vw"} - 128px, 1px), 1640px), 1px) - 32px) / 2, 1px)`}
											y={
												(componentViewport?.y || 0) +
												52 +
												0 +
												0 +
												145.17 +
												0 +
												0 +
												204
											}
											{...addPropertyOverrides2(
												{
													vfHOM_tY3: {
														width: `max(min(max(${componentViewport?.width || "100vw"} - 80px, 1px), 1640px), 1px)`,
														y:
															(componentViewport?.y || 0) +
															52 +
															0 +
															0 +
															145.17 +
															0 +
															612 +
															0 +
															204,
													},
													XiJfXJHW0: {
														width: `max(min(max(${componentViewport?.width || "100vw"} - 48px, 1px), 1640px), 1px)`,
														y:
															(componentViewport?.y || 0) +
															96 +
															0 +
															0 +
															129.17 +
															0 +
															612 +
															0 +
															204,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer2
												className={"framer-1mwro7a-container"}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"ARNdVJKDj-container"}
												nodeId={"ARNdVJKDj"}
												rendersWithMotion={true}
												scopeId={"DRR7m6of2"}
											>
												{_jsx2(stdin_default, {
													gweFQuELC: cOY7DLCd7,
													height: "100%",
													id: "ARNdVJKDj",
													layoutId: "ARNdVJKDj",
													style: {
														width: "100%",
													},
													variant: "GNe6SLWcd",
													width: "100%",
													x2_Q5XkAe: IdvJ8eZXu,
												})}
											</SmartComponentScopedContainer2>
										</ComponentViewportProvider2>
										<ComponentViewportProvider2
											height={172}
											width={`max((max(min(max(${componentViewport?.width || "100vw"} - 128px, 1px), 1640px), 1px) - 32px) / 2, 1px)`}
											y={
												(componentViewport?.y || 0) +
												52 +
												0 +
												0 +
												145.17 +
												0 +
												0 +
												408
											}
											{...addPropertyOverrides2(
												{
													vfHOM_tY3: {
														width: `max(min(max(${componentViewport?.width || "100vw"} - 80px, 1px), 1640px), 1px)`,
														y:
															(componentViewport?.y || 0) +
															52 +
															0 +
															0 +
															145.17 +
															0 +
															612 +
															0 +
															408,
													},
													XiJfXJHW0: {
														width: `max(min(max(${componentViewport?.width || "100vw"} - 48px, 1px), 1640px), 1px)`,
														y:
															(componentViewport?.y || 0) +
															96 +
															0 +
															0 +
															129.17 +
															0 +
															612 +
															0 +
															408,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer2
												className={"framer-15xoczb-container"}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"cRBEqQZL7-container"}
												nodeId={"cRBEqQZL7"}
												rendersWithMotion={true}
												scopeId={"DRR7m6of2"}
											>
												{_jsx2(stdin_default, {
													gweFQuELC: bgkvim21n,
													height: "100%",
													id: "cRBEqQZL7",
													layoutId: "cRBEqQZL7",
													style: {
														width: "100%",
													},
													variant: "GNe6SLWcd",
													width: "100%",
													x2_Q5XkAe: Wmsh2RifY,
												})}
											</SmartComponentScopedContainer2>
										</ComponentViewportProvider2>
									</motion2.div>
								</MotionDivWithFX>
							</motion2.div>
						</motion2.div>
					</motion2.section>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-o6Mjh.framer-60dac, .framer-o6Mjh .framer-60dac { display: block; }",
	".framer-o6Mjh.framer-1jnb3f6 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 52px 64px 52px 64px; position: relative; width: 1560px; }",
	".framer-o6Mjh .framer-fdmkpz { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; max-width: 1640px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-o6Mjh .framer-1ha7crw { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-o6Mjh .framer-1hylm0d { flex: none; height: auto; max-width: 600px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-o6Mjh .framer-19w8ofe { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-o6Mjh .framer-vo31t8, .framer-o6Mjh .framer-mihys { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-o6Mjh .framer-1hou1w6-container, .framer-o6Mjh .framer-o5k493-container, .framer-o6Mjh .framer-mb5kce-container, .framer-o6Mjh .framer-1bpl0ko-container, .framer-o6Mjh .framer-1mwro7a-container, .framer-o6Mjh .framer-15xoczb-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-o6Mjh.framer-v-og98it.framer-1jnb3f6 { width: 1200px; }",
	".framer-o6Mjh.framer-v-1yx5yko.framer-1jnb3f6 { padding: 52px 40px 52px 40px; width: 810px; }",
	".framer-o6Mjh.framer-v-1yx5yko .framer-19w8ofe, .framer-o6Mjh.framer-v-l4i17p .framer-19w8ofe { flex-direction: column; }",
	".framer-o6Mjh.framer-v-1yx5yko .framer-vo31t8, .framer-o6Mjh.framer-v-1yx5yko .framer-mihys, .framer-o6Mjh.framer-v-l4i17p .framer-vo31t8, .framer-o6Mjh.framer-v-l4i17p .framer-mihys { flex: none; width: 100%; }",
	".framer-o6Mjh.framer-v-l4i17p.framer-1jnb3f6 { padding: 96px 24px 96px 24px; width: 390px; }",
	".framer-o6Mjh.framer-v-l4i17p .framer-1ha7crw { gap: 64px; }",
];
var FramerDRR7m6of2 = withCSS2(Component2, css4, "framer-o6Mjh");
var stdin_default2 = FramerDRR7m6of2;
FramerDRR7m6of2.displayName = "FAQ";
FramerDRR7m6of2.defaultProps = {
	height: 618.5,
	width: 1560,
};
addPropertyControls2(FramerDRR7m6of2, {
	variant: {
		options: ["fdMpW_bv9", "Q8gO0cTJA", "vfHOM_tY3", "XiJfXJHW0"],
		optionTitles: ["Desktop", "Laptop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	WAQHLu5Ew: {
		defaultValue: "Toutes les montres sont-elles authentifi\xE9es ?",
		displayTextArea: true,
		placeholder: "",
		title: "QuestionUn",
		type: ControlType2.String,
	},
	JXlflnerm: {
		defaultValue:
			"Oui. Chaque montre est rigoureusement authentifi\xE9e par nos horlogers experts avant d\u2019\xEAtre mise en vente. Un certificat d\u2019authenticit\xE9 est d\xE9livr\xE9 pour chaque pi\xE8ce.",
		displayTextArea: true,
		title: "ReponseUn",
		type: ControlType2.String,
	},
	dGtOSqQm4: {
		defaultValue: "Proposez-vous une garantie sur les montres vendues ?",
		displayTextArea: true,
		placeholder: "",
		title: "QuestionDeux",
		type: ControlType2.String,
	},
	AgVIZixiY: {
		defaultValue:
			"Absolument. Nos montres b\xE9n\xE9ficient d\u2019une garantie commerciale allant de 12 \xE0 24 mois, selon le mod\xE8le et son \xE9tat. Les d\xE9tails sont pr\xE9cis\xE9s lors de l\u2019achat.",
		displayTextArea: true,
		title: "ReponseDeux",
		type: ControlType2.String,
	},
	mfph44fFR: {
		defaultValue: "Puis-je faire estimer ma montre gratuitement ?",
		displayTextArea: true,
		placeholder: "",
		title: "QuestionTrois",
		type: ControlType2.String,
	},
	zHKv5VQZb: {
		defaultValue:
			"Oui. Nous proposons un service d\u2019estimation gratuit, en boutique ou \xE0 distance via photos et r\xE9f\xE9rences. Un rendez-vous peut \xEAtre n\xE9cessaire pour une \xE9valuation pr\xE9cise.",
		displayTextArea: true,
		title: "ReponseTrois",
		type: ControlType2.String,
	},
	qGQchHvpF: {
		defaultValue: "Est-il possible de rechercher un mod\xE8le sp\xE9cifique ?",
		displayTextArea: true,
		placeholder: "",
		title: "QuestionQuatre",
		type: ControlType2.String,
	},
	KEz9G5LNo: {
		defaultValue:
			"Oui. Si un mod\xE8le n\u2019est pas disponible en stock, nous proposons un service de sourcing personnalis\xE9 pour trouver la pi\xE8ce exacte que vous recherchez.",
		displayTextArea: true,
		title: "ReponseQuatre",
		type: ControlType2.String,
	},
	IdvJ8eZXu: {
		defaultValue: "Exp\xE9diez-vous \xE0 l\u2019international ?",
		displayTextArea: true,
		placeholder: "",
		title: "QuestionCinq",
		type: ControlType2.String,
	},
	cOY7DLCd7: {
		defaultValue:
			"Oui. Nous assurons des livraisons s\xE9curis\xE9es en France et en Europe sous 24h \xE0 48h, via des transporteurs sp\xE9cialis\xE9s et assur\xE9s, avec suivi complet.",
		displayTextArea: true,
		title: "ReponseCinq",
		type: ControlType2.String,
	},
	Wmsh2RifY: {
		defaultValue: "Rachetez-vous les montres sans bo\xEEte ni papiers ?",
		displayTextArea: true,
		placeholder: "",
		title: "QuestionSix",
		type: ControlType2.String,
	},
	bgkvim21n: {
		defaultValue:
			"Oui, sous conditions. Nos experts \xE9valueront l\u2019authenticit\xE9 et l\u2019\xE9tat de la montre. La pr\xE9sence des papiers et de la bo\xEEte reste un atout pour maximiser la valeur.",
		displayTextArea: true,
		title: "ReponseSix",
		type: ControlType2.String,
	},
});
addFonts2(
	FramerDRR7m6of2,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Adam Medium Medium",
					source: "custom",
					url: "https://framerusercontent.com/assets/Wn1zzYTQUJupqavKKtLPzSagTA.woff2",
				},
			],
		},
		...AccordionFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "XiJfXJHW0",
	md: "vfHOM_tY3",
	xl: "Q8gO0cTJA",
	"2xl": "fdMpW_bv9",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e8637dcc282c405e8332e4eab2cb458a196f99fcac27567df85b0de9996f5033"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders FaqFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e8637dcc282c405e8332e4eab2cb458a196f99fcac27567df85b0de9996f5033"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var faq_default = ComponentWithRoot;
export { faq_default as default };
