// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e8637dcc282c405e "DaVinci Watches - Finale", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Laptop' | 'Tablet' | 'Phone' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { routes } from "./chunks/chunk-3QCU63GD.js";

// virtual:formulairevente
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/formulairevente-1uPg.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ImageWithFX = withFX(Image);
var cycleOrder = ["M15cn0n21", "fgXcPrk6L", "ZTdqPz3a5", "EixCat1xd"];
var serializationHash = "framer-ToAKS";
var variantClassNames = {
	EixCat1xd: "framer-v-1rxs892",
	fgXcPrk6L: "framer-v-aif30d",
	M15cn0n21: "framer-v-ifh3nt",
	ZTdqPz3a5: "framer-v-7jadch",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: -150,
	y: 0,
};
var transition2 = {
	damping: 50,
	delay: 0.1,
	mass: 1,
	stiffness: 100,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "M15cn0n21",
	Laptop: "fgXcPrk6L",
	Phone: "EixCat1xd",
	Tablet: "ZTdqPz3a5",
};
var getProps = ({ height, id, image, width, ...props }) => {
	return {
		...props,
		lQow17npR: image ??
			props.lQow17npR ?? {
				alt: "hotel",
				pixelHeight: 5317,
				pixelWidth: 3545,
				src: "https://framerusercontent.com/images/p1EhrjKqOc3Q1VahIGTGiG9lsQw.jpg?scale-down-to=2048",
				srcSet:
					"https://framerusercontent.com/images/p1EhrjKqOc3Q1VahIGTGiG9lsQw.jpg?scale-down-to=1024 682w,https://framerusercontent.com/images/p1EhrjKqOc3Q1VahIGTGiG9lsQw.jpg?scale-down-to=2048 1365w,https://framerusercontent.com/images/p1EhrjKqOc3Q1VahIGTGiG9lsQw.jpg?scale-down-to=4096 2730w,https://framerusercontent.com/images/p1EhrjKqOc3Q1VahIGTGiG9lsQw.jpg 3545w",
			},
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "M15cn0n21",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, lQow17npR, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "M15cn0n21",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-ifh3nt",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"M15cn0n21"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-3399e391-f9d3-4781-bcc9-e38e7cf0c7f5, rgb(249, 253, 254))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								EixCat1xd: {
									"data-framer-name": "Phone",
								},
								fgXcPrk6L: {
									"data-framer-name": "Laptop",
								},
								ZTdqPz3a5: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-xhikwj"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"To0CsuPAV"}
						>
							<motion.div
								className={"framer-14nqxnp"}
								data-framer-name={"Form"}
								layoutDependency={layoutDependency}
								layoutId={"tcAhwdmK3"}
							/>
						</motion.div>
						<ImageWithFX
							__framer__animate={{
								transition: transition2,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 68,
								),
								pixelHeight: 5317,
								pixelWidth: 3545,
								sizes: `calc(${componentViewport?.width || "100vw"} * 0.7)`,
								...toResponsiveImage(lQow17npR),
							}}
							className={"framer-79sb0b"}
							data-framer-name={"Image"}
							layoutDependency={layoutDependency}
							layoutId={"T2tUfi6du"}
							{...addPropertyOverrides(
								{
									EixCat1xd: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 68,
											),
											pixelHeight: 5317,
											pixelWidth: 3545,
											sizes: `calc(${componentViewport?.width || "100vw"} - 468px)`,
											...toResponsiveImage(lQow17npR),
										},
									},
									fgXcPrk6L: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 68,
											),
											pixelHeight: 5317,
											pixelWidth: 3545,
											sizes: `calc(${componentViewport?.width || "100vw"} * 0.61)`,
											...toResponsiveImage(lQow17npR),
										},
									},
									ZTdqPz3a5: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 68,
											),
											pixelHeight: 5317,
											pixelWidth: 3545,
											sizes: `calc(${componentViewport?.width || "100vw"} / 1.638)`,
											...toResponsiveImage(lQow17npR),
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ToAKS.framer-o27coa, .framer-ToAKS .framer-o27coa { display: block; }",
	".framer-ToAKS.framer-ifh3nt { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; overflow: visible; padding: 160px 64px 160px 64px; position: relative; width: 1560px; }",
	".framer-ToAKS .framer-xhikwj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; max-width: 1640px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-ToAKS .framer-14nqxnp { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; min-height: 798px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-ToAKS .framer-79sb0b { bottom: 92px; flex: none; left: 468px; position: absolute; top: 68px; width: 70%; z-index: 0; }",
	".framer-ToAKS.framer-v-aif30d.framer-ifh3nt { width: 1200px; }",
	".framer-ToAKS.framer-v-aif30d .framer-79sb0b { bottom: 93px; width: 61%; }",
	".framer-ToAKS.framer-v-7jadch.framer-ifh3nt { padding: 160px 40px 160px 40px; width: 1199px; }",
	".framer-ToAKS.framer-v-7jadch .framer-14nqxnp, .framer-ToAKS.framer-v-1rxs892 .framer-14nqxnp { min-height: 318px; }",
	".framer-ToAKS.framer-v-7jadch .framer-79sb0b { bottom: 92px; width: 61%; }",
	".framer-ToAKS.framer-v-1rxs892.framer-ifh3nt { padding: 160px 24px 160px 24px; width: 200px; }",
	".framer-ToAKS.framer-v-1rxs892 .framer-79sb0b { right: 0px; width: unset; }",
];
var FramerPdREk9hpe = withCSS(Component, css, "framer-ToAKS");
var stdin_default = FramerPdREk9hpe;
FramerPdREk9hpe.displayName = "formulairevente";
FramerPdREk9hpe.defaultProps = {
	height: 1117.5,
	width: 1560,
};
addPropertyControls(FramerPdREk9hpe, {
	variant: {
		options: ["M15cn0n21", "fgXcPrk6L", "ZTdqPz3a5", "EixCat1xd"],
		optionTitles: ["Desktop", "Laptop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	lQow17npR: {
		__defaultAssetReference:
			"data:framer/asset-reference,p1EhrjKqOc3Q1VahIGTGiG9lsQw.jpg?originalFilename=IMG_6506.jpg&preferredSize=auto",
		__vekterDefault: {
			alt: "hotel",
			assetReference:
				"data:framer/asset-reference,p1EhrjKqOc3Q1VahIGTGiG9lsQw.jpg?originalFilename=IMG_6506.jpg&preferredSize=auto",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerPdREk9hpe,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:formulairevente
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "EixCat1xd",
	md: "ZTdqPz3a5",
	xl: "fgXcPrk6L",
	"2xl": "M15cn0n21",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e8637dcc282c405e8332e4eab2cb458a196f99fcac27567df85b0de9996f5033"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders FormulaireventeFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e8637dcc282c405e8332e4eab2cb458a196f99fcac27567df85b0de9996f5033"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var formulairevente_default = ComponentWithRoot;
export { formulairevente_default as default };
