// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e8637dcc282c405e "DaVinci Watches - Finale", do not edit manually */
"use client";

// virtual:mentions
/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Laptop' | 'Tablet' | 'Phone' // Variant
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Mentions-mQ9o.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/uqFu4RTMtjsVvh5Yz0tU/AJMjhmuq668fUUevu4Ds/FfbbwYOZg.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;Hedvig Letters Sans-regular",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Hedvig Letters Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/hedvigletterssans/v2/CHy_V_PfGVjobSBkihHWDT98RVp37w8jQJhN3Twgi1w.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css = [
	'.framer-9XDCb .framer-styles-preset-17bssob:not(.rich-text-wrapper), .framer-9XDCb .framer-styles-preset-17bssob.rich-text-wrapper p { --framer-font-family: "Hedvig Letters Sans", "Hedvig Letters Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 25px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, #1e1e1e); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1559px) and (min-width: 1200px) { .framer-9XDCb .framer-styles-preset-17bssob:not(.rich-text-wrapper), .framer-9XDCb .framer-styles-preset-17bssob.rich-text-wrapper p { --framer-font-family: "Hedvig Letters Sans", "Hedvig Letters Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 23px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, #1e1e1e); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-9XDCb .framer-styles-preset-17bssob:not(.rich-text-wrapper), .framer-9XDCb .framer-styles-preset-17bssob.rich-text-wrapper p { --framer-font-family: "Hedvig Letters Sans", "Hedvig Letters Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 22px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, #1e1e1e); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-9XDCb .framer-styles-preset-17bssob:not(.rich-text-wrapper), .framer-9XDCb .framer-styles-preset-17bssob.rich-text-wrapper p { --framer-font-family: "Hedvig Letters Sans", "Hedvig Letters Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, #1e1e1e); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className = "framer-9XDCb";

// /:https://framerusercontent.com/modules/oLzxF6mrxE8QCutF3z8j/1P6HqsGNcL8ytJQyQzeN/fntKOO_Y7.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts(["CUSTOM;Adam Medium Medium"]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Adam Medium Medium",
				source: "custom",
				url: "https://framerusercontent.com/assets/Wn1zzYTQUJupqavKKtLPzSagTA.woff2",
			},
		],
	},
];
var css2 = [
	'.framer-lmGM4 .framer-styles-preset-xyzups:not(.rich-text-wrapper), .framer-lmGM4 .framer-styles-preset-xyzups.rich-text-wrapper h3 { --framer-font-family: "Adam Medium Medium", "Adam Medium Medium Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 39px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.33em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, #1e1e1e); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1499px) and (min-width: 1200px) { .framer-lmGM4 .framer-styles-preset-xyzups:not(.rich-text-wrapper), .framer-lmGM4 .framer-styles-preset-xyzups.rich-text-wrapper h3 { --framer-font-family: "Adam Medium Medium", "Adam Medium Medium Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 33px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.33em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, #1e1e1e); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-lmGM4 .framer-styles-preset-xyzups:not(.rich-text-wrapper), .framer-lmGM4 .framer-styles-preset-xyzups.rich-text-wrapper h3 { --framer-font-family: "Adam Medium Medium", "Adam Medium Medium Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 29px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.33em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, #1e1e1e); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-lmGM4 .framer-styles-preset-xyzups:not(.rich-text-wrapper), .framer-lmGM4 .framer-styles-preset-xyzups.rich-text-wrapper h3 { --framer-font-family: "Adam Medium Medium", "Adam Medium Medium Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 26px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.33em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-564427ef-92c1-4e0d-be6a-50ecc1afab8b, #1e1e1e); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className2 = "framer-lmGM4";

// /:https://framer.com/m/Mentions-mQ9o.js
var cycleOrder = ["uG2V1fl0G", "anI_OPhlp", "KBonAiSY0", "XgvuxLSb6"];
var serializationHash = "framer-rs6fH";
var variantClassNames = {
	anI_OPhlp: "framer-v-2cklqy",
	KBonAiSY0: "framer-v-jaozlj",
	uG2V1fl0G: "framer-v-hfi2oa",
	XgvuxLSb6: "framer-v-tbl3z5",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "uG2V1fl0G",
	Laptop: "anI_OPhlp",
	Phone: "XgvuxLSb6",
	Tablet: "KBonAiSY0",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "uG2V1fl0G",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "uG2V1fl0G",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-hfi2oa",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"uG2V1fl0G"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-3399e391-f9d3-4781-bcc9-e38e7cf0c7f5, rgb(249, 253, 254))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								anI_OPhlp: {
									"data-framer-name": "Laptop",
								},
								KBonAiSY0: {
									"data-framer-name": "Tablet",
								},
								XgvuxLSb6: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-jfy26m"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"BPyjFOzxg"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h3
									className={"framer-styles-preset-xyzups"}
									data-styles-preset={"fntKOO_Y7"}
								>
									{"INFORMATIONS \xC9DITEUR"}
								</motion.h3>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{"Da Vinci Consulting SAS"}
								</motion.p>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{"19 rue Jean Mermoz, 75008 Paris"}
								</motion.p>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{"SAS au capital de 10.000 euros"}
								</motion.p>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{"RCS Paris : 847 724 408"}
								</motion.p>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{"Identifiant communautaire EORI : FR84772440800012"}
								</motion.p>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{"N\xB0 TVA intracommunautaire : FR76 847 724 408"}
								</motion.p>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{"Directeur de la publication : Da Vinci Watches"}
								</motion.p>
								<motion.h3
									className={"framer-styles-preset-xyzups"}
									data-styles-preset={"fntKOO_Y7"}
								>
									{"DROIT D\u2019AUTEUR"}
								</motion.h3>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{
										"La pr\xE9sentation et le contenu de ce site constituent ensemble une oeuvre prot\xE9g\xE9e"
									}
								</motion.p>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{
										"par les conventions internationales et les lois en vigueur sur la propri\xE9t\xE9 intellectuelle"
									}
								</motion.p>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{
										"et notamment le droit d\u2019auteur, la concurrence d\xE9loyale et les marques d\xE9pos\xE9es."
									}
								</motion.p>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{
										"Aucune reproduction ou repr\xE9sentation ne peut avoir lieu sans le consentement \xE9crit"
									}
								</motion.p>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{
										"et pr\xE9alable de la soci\xE9t\xE9 DA VINCI CONSULTING SAS, propri\xE9taire de la marque"
									}
								</motion.p>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{"Da Vinci Watches d\xE9pos\xE9e aupr\xE8s de l\u2019INPI."}
								</motion.p>
								<motion.h3
									className={"framer-styles-preset-xyzups"}
									data-styles-preset={"fntKOO_Y7"}
								>
									{"INFORMATIONS H\xC9BERGEUR"}
								</motion.h3>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{"Soci\xE9t\xE9 OVH"}
								</motion.p>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{"RCS : 424 761 419"}
								</motion.p>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{
										"Si\xE8ge social : 2 rue Kellermann \u2013 59100 Roubaix \u2013 France."
									}
								</motion.p>
								<motion.h3
									className={"framer-styles-preset-xyzups"}
									data-styles-preset={"fntKOO_Y7"}
								>
									{"INFORMATIONS CONCEPTEUR"}
								</motion.h3>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{"D\xE9veloppement :  AMWD"}
								</motion.p>
								<motion.p
									className={"framer-styles-preset-17bssob"}
									data-styles-preset={"FfbbwYOZg"}
								>
									{"Cr\xE9dits photos : Da Vinci Consulting"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-rs6fH.framer-ucf9g9, .framer-rs6fH .framer-ucf9g9 { display: block; }",
	".framer-rs6fH.framer-hfi2oa { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 59px; height: min-content; justify-content: center; min-height: calc(var(--framer-viewport-height, 100vh) * 0.66); overflow: visible; padding: 0px 64px 0px 64px; position: relative; width: 1560px; }",
	".framer-rs6fH .framer-jfy26m { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-rs6fH.framer-v-2cklqy.framer-hfi2oa { padding: 160px 64px 0px 64px; width: 1200px; }",
	".framer-rs6fH.framer-v-jaozlj.framer-hfi2oa { padding: 160px 64px 0px 64px; width: 810px; }",
	".framer-rs6fH.framer-v-tbl3z5.framer-hfi2oa { padding: 29px 64px 0px 64px; width: 390px; }",
	".framer-rs6fH.framer-v-tbl3z5 .framer-jfy26m { width: 130%; }",
	...css2,
	...css,
];
var FramerfU2NKNM9P = withCSS(Component, css3, "framer-rs6fH");
var stdin_default = FramerfU2NKNM9P;
FramerfU2NKNM9P.displayName = "Mentions";
FramerfU2NKNM9P.defaultProps = {
	height: 1272.5,
	width: 1560,
};
addPropertyControls(FramerfU2NKNM9P, {
	variant: {
		options: ["uG2V1fl0G", "anI_OPhlp", "KBonAiSY0", "XgvuxLSb6"],
		optionTitles: ["Desktop", "Laptop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerfU2NKNM9P,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:mentions
import { WithFramerBreakpoints } from "unframer";

// virtual:__routes
var routes = {
	ABs8A7Jd4: {
		path: "/vente",
	},
	HqqUpNGKj: {
		path: "/",
	},
	X4ktpndPG: {
		path: "/erreur",
	},
	Xzx1dk12F: {
		path: "/latelier",
	},
	vAou7hwl6: {
		path: "/mentionslegales",
	},
	w6N05sxE8: {
		path: "/contact",
	},
};

// virtual:mentions
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "XgvuxLSb6",
	md: "KBonAiSY0",
	xl: "anI_OPhlp",
	"2xl": "uG2V1fl0G",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e8637dcc282c405e8332e4eab2cb458a196f99fcac27567df85b0de9996f5033"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders MentionsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e8637dcc282c405e8332e4eab2cb458a196f99fcac27567df85b0de9996f5033"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var mentions_default = ComponentWithRoot;
export { mentions_default as default };
